# Generated by Django 4.1.1 on 2022-09-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('note', models.DecimalField(decimal_places=2, max_digits=4)),
                ('age', models.IntegerField()),
                ('period', models.CharField(choices=[('Ensino Médio', 'Ensino Médio'), ('Ensino Fundamental', 'Ensino Fundamental'), ('Infantil', 'Infantil')], max_length=30)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
