# Generated by Django 4.1.1 on 2022-09-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='period',
            field=models.CharField(choices=[('Ensino Médio', 'Ensino Médio'), ('Ensino Fundamental', 'Ensino Fundamental'), ('Infantil', 'Infantil'), ('Faculdade', 'Faculdade')], max_length=30),
        ),
    ]
