# Generated by Django 4.1.1 on 2022-09-16 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_date_student_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='data_update',
            field=models.DateField(auto_now=True),
        ),
    ]
